print("---------------------------------------------------")
print("     Welcome to the Student Profile system    ")
print("---------------------------------------------------")
print("This program collects your details and displays a formatted student profile.\n")

full_name = input("Enter your full name: ")
roll_number = input("Enter your roll number: ")
program = input("Enter your program (e.g., BCA): ")
university = input("Enter your University name: ")
city = input("Enter your city: ")
age = int(input("Enter your age: "))
hobby = input("Enter your hobby: ")

print("\nThank you! Your details have been recorded.\n")

print("--------- Operator Demonstration ---------")

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print("\nArithmetic Operators:")
print(f"{num1} + {num2} = {num1 + num2}")
print(f"{num1} - {num2} = {num1 - num2}")
print(f"{num1} * {num2} = {num1 * num2}")
print(f"{num1} / {num2} = {num1 / num2}")
print(f"{num1} % {num2} = {num1 % num2}")
print(f"{num1} ** {num2} = {num1 ** num2}")
print(f"{num1} // {num2} = {num1 // num2}")
print("\nAssignment Operators:")
a = num1
a += num2
print(f"a += num2 → {a}")
a -= num2
print(f"a -= num2 → {a}")
a *= 2
print(f"a *= 2 → {a}")
print("\nComparison Operators:")
print(f"{num1} == {num2}: {num1 == num2}")
print(f"{num1} != {num2}: {num1 != num2}")
print(f"{num1} > {num2}: {num1 > num2}")
print(f"{num1} < {num2}: {num1 < num2}")
print("\nLogical Operators:")
print(f"({num1} > 0) and ({num2} > 0): {(num1 > 0) and (num2 > 0)}")
print(f"({num1} > 0) or ({num2} < 0): {(num1 > 0) or (num2 < 0)}")
print(f"not({num1} > {num2}): {not(num1 > num2)}")
print("\nIdentity Operators:")
print(f"num1 is num2: {num1 is num2}")
print(f"num1 is not num2: {num1 is not num2}")
print("\nMembership Operators:")
text = "Welcome to Python Programming"
print(f"'Python' in text: {'Python' in text}")
print(f"'Java' not in text: {'Java' not in text}")
print("\n--------- String Operations ---------")
print("Original name:", full_name)
print("Uppercase:", full_name.upper())
print("Lowercase:", full_name.lower())
print("Title case:", full_name.title())
print("Replaced spaces with underscores:", full_name.replace(" ", "_"))
print("Count of letter 'a' in name:", full_name.count('a'))
formatted_intro = f"\nHello, {full_name}!\n\tWelcome to \"{university}\" located in {city}.\n\tWe hope you enjoy your journey in the {program} program!\n"
print(formatted_intro)
print("----------------------------------------")
print("        STUDENT PROFILE SYSTEM          ")
print("----------------------------------------")
print(f"Name:            {full_name}")
print(f"Roll No:         {roll_number}")
print(f"Course:          {program}")
print(f"University:      {university}")
print(f"City:            {city}")
print(f"Age:             {age}")
print(f"Hobby:           {hobby}")
print("----------------------------------------")
print("Welcome to Python Programming !")
print("----------------------------------------")
save_choice = input("\nDo you want to save your profile to a file? (yes/no): ").strip().lower()
if save_choice == "yes":
    with open("student_profile.txt", "w") as file:
        file.write("----------------------------------------\n")
        file.write("        STUDENT PROFILE SYSTEM          \n")
        file.write("----------------------------------------\n")
        file.write(f"Name:            {full_name}\n")
        file.write(f"Roll No:         {roll_number}\n")
        file.write(f"Course:          {program}\n")
        file.write(f"University:      {university}\n")
        file.write(f"City:            {city}\n")
        file.write(f"Age:             {age}\n")
        file.write(f"Hobby:           {hobby}\n")
        file.write("----------------------------------------\n")
        file.write("Welcome to Python Programming !\n")
    print("Profile successfully saved to 'student_profile.txt'")
else:
    print("Profile not saved. Exiting program.")

print("\nThank you for using the Student Profile system ")